name: Check

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    ci:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python 3.12
              uses: actions/setup-python@v5
              with:
                  python-version: 3.12

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -e .[dev]

            - name: Run tests
              run: |
                  pytest

            - name: Run linters
              run: |
                  black --check .
                  autoflake --check --recursive .

            - name: Run mypy
              run: |
                  mypy .
